Traceback (most recent call last):
  File "/work/henriksv/code/mario-data-collection/mario_dqn/plots/compare_multiple.py", line 141, in <module>
    compare(paths, legends, 'scores', label,test, 7000, 1000)
  File "/work/henriksv/code/mario-data-collection/mario_dqn/plots/compare_multiple.py", line 16, in compare
    data.append(json.load(json_file))
  File "/home/henriksv/anaconda3/envs/tf2/lib/python3.7/json/__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "/home/henriksv/anaconda3/envs/tf2/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/henriksv/anaconda3/envs/tf2/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/henriksv/anaconda3/envs/tf2/lib/python3.7/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 1 column 491777 (char 491776)
srun: error: g001: task 0: Exited with exit code 1
